// tiendaLineaReact/src/producto.jsx
import React from 'react'
import './producto.css'

class Producto extends React.Component{


    render(){
        return(
             //html de detalle   
             <div className="detalle">
             <h3>{this.props.detallado.nombre}</h3>
             <hr></hr>
             <div className="contenido" >
               <img src={"img/"+this.props.detallado.imagen} alt=""></img>
               <div className="descripcion">
                 <p><b>Precio: </b>$ {this.props.detallado.precio}</p>
                 <p><b>Unidades Disponibles: </b>{this.props.detallado.unidades}</p>
               </div>
             </div>
             <button className="btn btn-primary" onClick={()=>{this.retornarCatalogo()}}>Atrás</button>
           </div>
        )
    }

    retornarCatalogo(){
      console.log("[HIJO] VENTANA ACTIVA: " + 1 )
      this.props.ventana(1)
    }
}

export default Producto

// tiendaLinea/src/app/main-tienda/producto/producto.component.ts
import { Component, OnInit } from '@angular/core';
import { OperacionesService } from './../../operaciones.service';

@Component({
  selector: 'app-producto',
  templateUrl: './producto.component.html',
  styleUrls: ['./producto.component.css']
})
export class ProductoComponent implements OnInit {

  item: any

  constructor(public operaciones: OperacionesService) { }

  ngOnInit() {

  }

  esconder(){
    this.operaciones.componenteActivo = 0
  }

}


<div class="detalle" *ngFor = "let articulo of this.operaciones.productoDetalle" [ngClass] =  "{oculto: this.operaciones.getComponenteActivo() != 1 }">
  <h3>{{articulo.nombre}}</h3>
  <hr>
  <div class="contenido" >
    <img src="./../../../assets/imagenesBase/{{articulo.imagen}}" alt="">
    <div class="descripcion">
      <p><b>Precio: </b>$ {{articulo.precio}}</p>
      <p><b>Unidades Disponibles: </b>{{articulo.unidades}}</p>
    </div>
  </div>
  <button class="btn btn-outline-primary" (click)="esconder()">Atrás</button>
</div>
