// tiendaLinea/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from 'src/app/http.service';
import { Router } from '@angular/router';
import { FormControl, Validators, FormGroup } from '@angular/forms';
import { OperacionesService } from '../operaciones.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  formlogin: FormGroup
  no_login: false
  
  constructor(public http: HttpService, private operaciones: OperacionesService, private router: Router){}

  logearse(user: string, clave: string, event: Event){
    event.preventDefault()
    
    this.http.login(user, clave)
    .subscribe((data: any)=>{
      if(data.login === 'YES'){
        this.operaciones.no_login = true
        sessionStorage.setItem('user', user)
        this.router.navigate(["tienda"])
      }
    })
  }

  ngOnInit(){
    //setea login a false
    // this.httpService.setLoginStatus(false)
    
    // define validacion del formulario los elementos de login
    this.formlogin = new FormGroup({
      'usuario' : new FormControl('', Validators.required),
      'contrasena' : new FormControl('', Validators.required)
    })
    
  }
}

<div class="a container-fluid">
        <img src="/assets/imagenesBase/login-fondo.jpg" alt="">
        <div class="row">
            <form [formGroup]="formlogin" class="login" (ngSubmit)="logearse(user.value, clave.value, $event)">
                <h3>Iniciar Sesion</h3>
                <label for="correo">Correo Electrónico:</label>
                <input type="text" #user formControlName = "usuario" pattern="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" required>
                <label for="clave">Contraseña:</label>
                <input type="password" #clave formControlName = "contrasena" required>
                <label class="error" *ngIf=no_login>No se ha podido hacer log in - Datos incorrectos!</label>
                <button class="btn btn-success" type="submit" [disabled] = "!formlogin.valid">Ingresar</button>
            </form>
        </div>

        
</div>

// tiendaLineaReact/src/login.jsx
import React from 'react'
import ReactDOM from 'react-dom'

import App from './App.jsx'
import './login.css'
import $ from 'jquery'

class LoginComponent extends React.Component{
    constructor(props){
        super(props)

        this.state ={
            mensaje: " "
        }

        this.cambiarMensajeLogin = this.cambiarMensajeLogin.bind(this)
        this.login=this.login.bind(this)
    }

    render(){
        return(
        <div className="a container-fluid">
        <img src="./img/login-fondo.jpg" alt="" className="loginFondo"></img>
            <div className="row">
                <form className="login" onSubmit={this.login}>
                    <h3>Iniciar Sesion</h3>
                    <label htmlFor="correo">Correo Electrónico:</label>
                    <input type="text" pattern="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$" required></input>
                    <label htmlFor="clave">Contraseña:</label>
                    <input type="password" required></input>
                    <label className="error">{this.state.mensaje}</label>
                    <button className="btn btn-success" type="submit">Ingresar</button>
                </form>
            </div>
        </div>
        )
    }

    
    login(){
        //funcion para hacer login en paginia login
        event.preventDefault()
            let user = $('input[type="text"]').val()    
            let pass = $('input[type="password"]').val()
            fetch('http://localhost:3000/login', {
                method: 'POST',
                body: JSON.stringify({correo: user, clave: pass}),
                headers:{
                    'Content-Type': 'application/json'
                  }
            }).then(res => res.json())
            .then(response => {
                if(response.login !== "YES")
                    this.cambiarMensajeLogin()
                else
                    ReactDOM.render(<App/>, document.getElementById('app'))   
            })       
    }

    cambiarMensajeLogin(){
        this.setState({mensaje: 'Datos incorrectos! No hay Log in'})
    }
    
}

export default LoginComponent
