// tiendaLineaReact/src/barraNavegacion.jsx
import React from 'react';
import './barraNavegacion.css'

class BarraNavegacion extends React.Component{

    constructor(){
        super()
    }

    render(){
        return(
            <div className="navbar">
                <a href="" className="navbar-brand">TiendaFrutas</a>      
                <div className="right">
                    <li className='material-icons' onClick = {()=>{this.setVentana(1)}}>menu</li>
                    <li className='material-icons' onClick = {()=>{this.setVentana(3)}}>shopping_cart
                    <span className="badge badge-pill badge-danger">{this.numeroEscogidos()}</span>
                    </li>
                    <li className='material-icons'>payment</li>
                    <li className='material-icons'>logout</li>
                </div> 
            </div>
        )
    }

    numeroEscogidos(){
        var respuesta = this.props.numEscogidos
        if( respuesta == 0)
            respuesta = ''
        
        return respuesta    
    }

    setVentana(valor){
        this.props.ventana(valor)
    }
    
}


export default BarraNavegacion

// tiendaLinea/src/app/main-tienda/barra-navegacion/barra-navegacion.component.ts
import { Component, OnInit } from '@angular/core';
import { OperacionesService } from 'src/app/operaciones.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-barra-navegacion',
  templateUrl: './barra-navegacion.component.html',
  styleUrls: ['./barra-navegacion.component.css']
})
export class BarraNavegacionComponent implements OnInit {

  constructor(public operaciones: OperacionesService, private router: Router) { }

  ngOnInit() {
  }

  logout(){
    this.operaciones.no_login=false
    this.router.navigate([''])
    localStorage.removeItem('user')
  }
}


    <div class="navbar">
        <a href="" class="navbar-brand">TiendaFrutas</a>      
           <div class="right">
                <li class='material-icons' (click) = "this.operaciones.setComponenteActivo(0)">menu</li>
                <li class='material-icons' (click) = "this.operaciones.setComponenteActivo(2)"  >shopping_cart 
                    <span class="badge badge-pill badge-danger" *ngIf = "this.operaciones.productosEscogidos.length > 0" [innerText]="this.operaciones.productosEscogidos.length"></span>
                </li>
                <li class='material-icons'>payment</li>
                <li class='material-icons' (click)= "this.logout()">logout</li>
           </div> 
    </div>
